
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  email VARCHAR(64) NOT NULL UNIQUE,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  roles VARCHAR(128) NOT NULL,
  name VARCHAR(64) NOT NULL,
  tickets INT(8) NOT NULL DEFAULT 0,
  birthday DATE NOT NULL DEFAULT '3000-01-01',
  systemMessage VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS events (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT '3000-01-01',
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  auditorium_id INT,
  image_url VARCHAR(255) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS tickets (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL,
  event_id INT NOT NULL,
  price INT NOT NULL,
  date TIMESTAMP NOT NULL,
  seat INT NOT NULL
);

CREATE TABLE IF NOT EXISTS auditoriums (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(64) NOT NULL,
  seats INT NOT NULL,
  vipSeats VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS counters (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(64) NOT NULL,
  type VARCHAR(16) NOT NULL,
  key INT NOT NULL,
  value INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_accounts (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL,
  money_prepaid INT DEFAULT 0
)
