//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.04.13 at 09:21:13 PM EEST
//


package ua.kh.bars.soap;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="event" type="{http://bars.kh.ua/soap}event"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "event"
})
@XmlRootElement(name = "FindEventByIdResponse")
public class FindEventByIdResponse {

    @XmlElement(required = true)
    protected Event event;

    /**
     * Gets the value of the event property.
     *
     * @return
     *     possible object is
     *     {@link Event }
     *
     */
    public Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     *
     * @param value
     *     allowed object is
     *     {@link Event }
     *
     */
    public void setEvent(Event value) {
        this.event = value;
    }

}
