//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 09:21:13 PM EEST 
//


package ua.kh.bars.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.kh.bars.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.kh.bars.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindUserByEmailResponse }
     * 
     */
    public FindUserByEmailResponse createFindUserByEmailResponse() {
        return new FindUserByEmailResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link FindUserByNameRequest }
     * 
     */
    public FindUserByNameRequest createFindUserByNameRequest() {
        return new FindUserByNameRequest();
    }

    /**
     * Create an instance of {@link FindUserByIdRequest }
     * 
     */
    public FindUserByIdRequest createFindUserByIdRequest() {
        return new FindUserByIdRequest();
    }

    /**
     * Create an instance of {@link RegisterUserRequest }
     * 
     */
    public RegisterUserRequest createRegisterUserRequest() {
        return new RegisterUserRequest();
    }

    /**
     * Create an instance of {@link FindUsersByNameRequest }
     * 
     */
    public FindUsersByNameRequest createFindUsersByNameRequest() {
        return new FindUsersByNameRequest();
    }

    /**
     * Create an instance of {@link FindEventByIdRequest }
     * 
     */
    public FindEventByIdRequest createFindEventByIdRequest() {
        return new FindEventByIdRequest();
    }

    /**
     * Create an instance of {@link FindUserByNameResponse }
     * 
     */
    public FindUserByNameResponse createFindUserByNameResponse() {
        return new FindUserByNameResponse();
    }

    /**
     * Create an instance of {@link FindUsersByNameResponse }
     * 
     */
    public FindUsersByNameResponse createFindUsersByNameResponse() {
        return new FindUsersByNameResponse();
    }

    /**
     * Create an instance of {@link RegisterUserResponse }
     * 
     */
    public RegisterUserResponse createRegisterUserResponse() {
        return new RegisterUserResponse();
    }

    /**
     * Create an instance of {@link FindUserByEmailRequest }
     * 
     */
    public FindUserByEmailRequest createFindUserByEmailRequest() {
        return new FindUserByEmailRequest();
    }

    /**
     * Create an instance of {@link FindEventByIdResponse }
     * 
     */
    public FindEventByIdResponse createFindEventByIdResponse() {
        return new FindEventByIdResponse();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link FindUserByIdResponse }
     * 
     */
    public FindUserByIdResponse createFindUserByIdResponse() {
        return new FindUserByIdResponse();
    }

}
